### ISSUE TITLE
Add plugin eslint-nibble

### ISSUE THREAD

**Issue by zckrs** [dustinspecker/awesome-eslint#13]
Can you add eslint-nibble in the awesome list ?

[Ease into ESLint, by fixing one rule at a time](https://github.com/IanVS/eslint-nibble)

/cc @IanVS

**Comment by sadorlovsky** [comment]
Yes, it's awesome tool! But, don't you want to make a PR?

**Comment by IanVS** [comment]
Great, I'm glad you find it useful.  😃
