### ISSUE TITLE
Additions order

### ISSUE THREAD

**Issue by sadorlovsky** [dustinspecker/awesome-eslint#15]
[Contribution guidelines](https://github.com/dustinspecker/awesome-eslint/blob/master/contributing.md) says that link additions should be added to the bottom of the relevant category.

Should we change them to follow alphabetical order?

**Comment by dustinspecker** [comment]
Yep, we should change the guidelines to say alphabetical (if you're cool keeping it alphabetical). Looks like I should read the contributions guidelines as well. 😃
