### ISSUE TITLE
Announcing one's tools

### ISSUE THREAD

**Issue by brettz9** [dustinspecker/awesome-eslint#161]
ESLint has a Discord server along with a specific room #lookwhatimade : https://discord.com/channels/688543509199716507/710284382321115186

Submitters here of their own projects might wish to announce their changes also on that channel.

@dustinspecker , just thought I could inform users with this issue, and if you like, pin this issue so new submitters might see it.

**Comment by dustinspecker** [comment]
This is a great idea - thank you! I'll pin this.
