### ISSUE TITLE
Plugin for Angular (v2+)

### ISSUE THREAD

**Issue by jdussouillez** [dustinspecker/awesome-eslint#180]
You have the "eslint-plugin-angular" package in your list but it's only for AngularJS (= Angular v1, deprecated).

An awesome one (maintained and widely used) for Angular (not AngularJS) is https://github.com/angular-eslint/angular-eslint

**Comment by dustinspecker** [comment]
That is awesome to see. Do you mind making a pull request to add it to this list?

**Comment by jdussouillez** [comment]
@dustinspecker Done is #182
