### ISSUE TITLE
eslint-plugin-tailwindcss 

### ISSUE THREAD

**Issue by francoismassart** [dustinspecker/awesome-eslint#199]
👋🏻 
Would you consider adding eslint-plugin-tailwindcss ?
Self advertising it is 😅
https://github.com/francoismassart/eslint-plugin-tailwindcss 

Let me know if you need me to create a pull request 🙏🏻

**Comment by francoismassart** [comment]
#200

**Comment by dustinspecker** [comment]
Closed by #200
