### ISSUE TITLE
how to know if a plugin is useful ?

### ISSUE THREAD

**Issue by veggiemonk** [dustinspecker/awesome-eslint#2]
Hi, 

I often use recursion (nested JSON object coming the backend) and this plugin [no-inferred-method-name](https://github.com/johnstonbl01/eslint-no-inferred-method-name) caught a few errors that would have taken me some times to figure out. 

This is quite useful to me but I wonder if it has its place and if it is where to put it?

**Comment by sadorlovsky** [comment]
Thanks! It seems to be pretty useful. This is right place for it, why not? I think we can put it in General section for now.

Can you make a PR to add it?
