### ISSUE TITLE
Replace prettier-standard by official prettier config

### ISSUE THREAD

**Issue by alcpereira** [dustinspecker/awesome-eslint#211]
As recommended by [Prettier docs](https://prettier.io/docs/en/integrating-with-linters.html), you should use the [official prettier eslint config](https://github.com/prettier/eslint-config-prettier) instead of using eslint plugins. I think `prettier-standard` falls in this category and should not be recommended in this list.

I can make a PR for this if you want.

**Comment by B2o5T** [comment]
also, he doesn't maintained

**Comment by dustinspecker** [comment]
@alcpereira A pull request would be awesome for this change.
