### ISSUE TITLE
PR for eslint-plugin-flowtype-errors

### ISSUE THREAD

**Issue by amilajack** [dustinspecker/awesome-eslint#39]
This plugin reports flow errors as ESLint errors.

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

https://github.com/amilajack/eslint-plugin-flowtype-errors

Would a PR for this be welcome?

**Comment by jfmengels** [comment]
Ooh this is interesting. Please make a PR :)
