### ISSUE TITLE
RFC: Add `eslint-plugin-compat`

### ISSUE THREAD

**Issue by amilajack** [dustinspecker/awesome-eslint#45]
This eslint plugin lints against APIs that are only supported by target browsers 🎉 Would a PR for adding this plugin be welcome?

**Here's a demo of it in action**

![demo of plugin usage](https://raw.githubusercontent.com/amilajack/eslint-plugin-compat/master/eslint-plugin-compat-demo.gif)

**Comment by jfmengels** [comment]
Absolutely :)

**Comment by ntwb** [comment]
As an aside, from a quick peek, @amilajack have you thought about using browserlist?

https://github.com/ai/browserslist

**Comment by amilajack** [comment]
@ntwb What does browserlist do?

**Comment by ntwb** [comment]
@amilajack It also uses the caniuse database, though you can have much more detailed queries of what browsers to test against, check the examples at https://github.com/ai/browserslist#queries

**Comment by amilajack** [comment]
@ntwb I see. So are you suggesting that `eslint-plugin-compat` use `browserslist` to query caniuse? `eslint-plugin-compat` is aimed at linting the cross-browser compatibility of apis being used. `browserslist` 'Shares browsers list between different front-end tools'. Two very different things
