### ISSUE TITLE
improve linting results step-by-step

### ISSUE THREAD

**Issue by michal-autin** [dustinspecker/awesome-eslint#85]
Hi

Thanks a lot for this list.
I ran out of options. I need some tool to allow me to compare linting errors and warnings on current working branch with some code baseline, not to allow new (more) errors/warnings than it was before. I used to have such a tool configured for TravisCI long time ago, but I'm not able to reverse-engineer that solution. Do you have any ideas? Maybe I just didn't found good google search phrase?

Regards

**Comment by davidjbradshaw** [comment]
This is most likely the closest thing to what your after. 

https://github.com/okonet/lint-staged

**Comment by dustinspecker** [comment]
I'm going to close this. Please feel free to re-open if you'd like to.
